id = "mermaid-preview"
name = "Mermaid Preview"
description = "Mermaid diagram language server for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <you@example.com>"]

[compatibility]
zed = "*"
min_zed_version = "0.133.0"

# Language server for Mermaid rendering
[language_servers.mermaid]
name = "Mermaid"
languages = ["Markdown"]