id = "mermaid-preview"
name = "Mermaid Preview"
description = "Render Mermaid diagrams from Markdown or .mmd files"
version = "0.4.5"
schema_version = 1
authors = ["Mermaid Preview Maintainers"]
repository = "https://github.com/dawsh2/zed-mermaid-preview"

[compatibility]
zed = "0.210.0"

# Language server for Mermaid rendering
[language_servers.mermaid]
name = "Mermaid LSP"
languages = ["Markdown", "Mermaid"]

[language_servers.mermaid.language_ids]
"Markdown" = "markdown"
"Mermaid" = "mermaid"
